### ISSUE TITLE
I wasn't able to run your code

### ISSUE THREAD

**Issue by OzanKurt** [KeepBotting/SRi#1]
Can you explain how to run the code?

Maybe we can talk on skype or something?

**Comment by KeepBotting** [comment]
You're not meant to run any of this code directly. SRi is an [include](https://www.freepascal.org/docs-html/user/usersu8.html) that you are meant to add to your own project, and use to create a script.

I will add some example scripts in the near-future, once a few more of the important features are functioning properly. I will also document general usage: these files are targeted at a very specific editor (Simba) and interpreter (Lape) and probably will not work elsewhere outside of that environment.

Sorry, I do not use Skype. I am reachable by email (found on my profile), or I can sometimes be found on IRC [here](https://villavu.com/forum/chat_irc.php) (#srl @ Rizon).

**Comment by OzanKurt** [comment]
I’m aware of the things you mentioned, I will wait for those example scripts. 

Thanks!

**Comment by KeepBotting** [comment]
I've added [USAGE.md](https://github.com/KeepBotting/SRi/blob/master/USAGE.md) which contains instructions for running the code. I'll close this issue now, feel free to reopen or contact me using any of the above methods.

**Comment by OzanKurt** [comment]
I used to code with SRL, not a contributor there.
